name: Push actions

on:
  push:
    branches:
      - main
      - dev
    tags:
      - '*'

jobs:
  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v3"
      - name: Setup Python
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.10"
      - name: Install requirements
        run: python3 -m pip install -r requirements_test.txt -r requirements_release.txt
      - name: Run tests
        run: |
          python3 -m pytest \
            -vv \
            -qq \
            --timeout=9 \
            --durations=10 \
            --cov podpointclient \
            --cov-report term \
            --cov-report html \
            -o console_output_style=count \
            -p no:sugar \
            tests
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: htmlcov/*
      - name: Build release package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: make package
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
